name: Test
run-name: Test

on:
  push:
    branches: "main"

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "Dev"
        type: choice
        options:
          - Dev
          - QA
          - Rek
